services:
    graph_client_bundle.model:
        class: GraphClientPhp\Model\ApiModel
        autowire: false
        arguments: # Setting in DI/GraphClientExtension.php
            - ""
            - ""
            - ""
        public: true

    graph_client_bundle.logger:
        class: GraphClientBundle\Logger\Logger
        autowire: false
        arguments: [""] # Setting in DI/GraphClientExtension.php

    graph_client_bundle.bridge:
        class: GraphClientBundle\Bridge\Bridge
        autowire: false
        arguments:
            - "@graph_client_bundle.model"
            - "@graph_client_bundle.logger"
        public: true

    graph_client_bundle.adapter:
        class: Symfony\Component\Cache\Adapter\PhpArrayAdapter
        autowire: false
        arguments: ["%kernel.cache_dir%/graph-client-bundle/cache.php", "@cache.app"]
        public: true

    graph_client_bundle.parser:
        class: GraphClientPhp\Parser\QueryBasicQueryParser
        autowire: false
        public: true

    graph_client_bundle.cache:
        class: GraphClientPhp\Cache\BasicCache
        autowire: false
        arguments:
            - "@graph_client_bundle.adapter"
            - "@graph_client_bundle.parser"
            - ""
            - ""

    graph_client_bundle.warmer:
        class: GraphClientBundle\Cache\CacheWarmer
        autowire: false
        arguments:
            - "@graph_client_bundle.cache"
        tags:
            - { name: kernel.cache_warmer }

    graph_client_bundle.client:
        class: GraphClientPhp\Client\BasicClient
        autowire: false
        arguments:
            - "@graph_client_bundle.bridge"
            - "@graph_client_bundle.parser"
        public: true

    graph_client_bundle.collector:
        class: GraphClientBundle\Collector\Collector
        autowire: false
        arguments: ["@graph_client_bundle.logger"]
        tags:
            - { name: data_collector, id: 'graph-client-bundle.collector', template: '@GraphClient/collector/graph-client.html.twig' }
